/* autogenerated by Processing revision 1286 on 2022-11-11 */
import processing.core.*;
import processing.data.*;
import processing.event.*;
import processing.opengl.*;

import java.util.HashMap;
import java.util.ArrayList;
import java.io.File;
import java.io.BufferedReader;
import java.io.PrintWriter;
import java.io.InputStream;
import java.io.OutputStream;
import java.io.IOException;

public class Boleta extends PApplet {

int posX, posY;

 public void setup () {
    /* size commented out by preprocessor */;
    posX = 320;
    posY = 40;
}

 public void draw () {
    clear();
    background(255);
    fill(0);
    ellipse(posX, posY, 30, 30);

    posY = posY + 2;

}


  public void settings() { size(640, 480); }

  static public void main(String[] passedArgs) {
    String[] appletArgs = new String[] { "--full-screen", "--bgcolor=#666666", "--stop-color=#cccccc", "Boleta" };
    if (passedArgs != null) {
      PApplet.main(concat(appletArgs, passedArgs));
    } else {
      PApplet.main(appletArgs);
    }
  }
}
